declare module 'types:Card' {
  // Generated by https://quicktype.io

  export interface ApiCard {
    id: string;
    name: string;
    supertype: string;
    subtypes: string[];
    hp: string;
    types: string[];
    attacks: Attack[];
    weaknesses: Weakness[];
    retreatCost: string[];
    convertedRetreatCost: number;
    set: Set;
    number: string;
    artist: string;
    rarity: string;
    flavorText: string;
    nationalPokedexNumbers: number[];
    legalities: Legalities;
    regulationMark: string;
    images: CardImages;
    tcgplayer: Tcgplayer;
    cardmarket: Cardmarket;
  }

  export interface Attack {
    cost: string[];
    name: string;
    damage: string;
    text: string;
    convertedEnergyCost: number;
  }

  export interface Cardmarket {
    url: string;
    updatedAt: string;
    prices: { [key: string]: number };
  }

  export interface CardImages {
    small: string;
    large: string;
  }

  export interface Legalities {
    unlimited: string;
    standard: string;
    expanded: string;
  }

  export interface Set {
    id: string;
    name: string;
    series: string;
    printedTotal: number;
    total: number;
    legalities: Legalities;
    releaseDate: string;
    updatedAt: string;
    images: SetImages;
  }

  export interface SetImages {
    symbol: string;
    logo: string;
  }

  export interface Tcgplayer {
    url: string;
    updatedAt: string;
    prices: Prices;
  }

  export interface Prices {
    normal: Normal;
    reverseHolofoil: Normal;
  }

  export interface Normal {
    low: number;
    mid: number;
    high: number;
    market: number;
    directLow: number;
  }

  export interface Weakness {
    type: string;
    value: string;
  }
}
